// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReactHooksTemplate = require("./app.bs.js");
var Component1$ReactHooksTemplate = require("./Component1.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component1$ReactHooksTemplate.make, {
          message: "Hello! Click this text."
        }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactHooksTemplate.make, {
          greeting: "My Grid"
        }), "app");

/*  Not a pure module */
